### PR TITLE
Fix failing test

### LINKED ISSUE #153: Fix failing test
https://travis-ci.org/yeoman/update-notifier/jobs/512463652

### PR DESCRIPTION
**Pull request by LitoMore**
Fix #153

### CODE REVIEW

File: test/notify.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ function Control(shouldNotifyInNpmScript) {
 const setupTest = isNpmReturnValue => {
 	['..', 'is-npm'].forEach(clearModule);
 	process.stdout.isTTY = true;
-	mock('is-npm', isNpmReturnValue || false);
+	mock('is-npm', {isNpm: isNpmReturnValue || false});
```
Comment (LitoMore) [inline test/notify.js]: The API of [is-npm@3.0.0](https://github.com/sindresorhus/is-npm) has been changed. So I updated the mock export.

File: package.json [hunk 2]
```diff
@@ -13,7 +13,7 @@
 		"node": ">=8"
 	},
 	"scripts": {
-		"test": "xo && ava --timeout=20s"
+		"test": "xo && ava --timeout=20s -s"
```
Comment (LitoMore) [inline package.json]: We should run tests serially for solving the conflict of mock require.

**Comment by SBoudrias** [comment]
Thanks!!
